[augdata]
git-tree-sha1 = "9763ec59f819802d0930ea6c36fb8b0075902c58"
lazy = true

    [[augdata.download]]
    sha256 = "b801491280f3871b0edc306645d4ff6ce3e6ed1081339037992d9748ee20531c"
    url = "https://virtual-worlds.biz/artifacts//augdata.tar.gz"

[disability]
git-tree-sha1 = "288ef84eac1aad34af423852e64001e75be3b822"
lazy = true

    [[disability.download]]
    sha256 = "7ed1e796fc2e09a4c48f772ea3cd06b7c6aab721c183f6905b2fa83890d0184b"
    url = "http://stb-artifacts/disability.tar.gz"

[exampledata]
git-tree-sha1 = "7853136d3530ea531e4f45a29f8fcef81d08fc1c"
lazy = true

    [[exampledata.download]]
    sha256 = "c426f605704bde8c79df3573a4f150512614480aa00f900893accaf75408463c"
    url = "https://virtual-worlds.biz/artifacts//exampledata.tar.gz"

[scottish-frs-data]
git-tree-sha1 = "93c84f080708295da9a62988d1aa23eb778f4143"
lazy = true

    [[scottish-frs-data.download]]
    sha256 = "f44f3e3ddf732923d58450eab316312e42d9c135e8eb6fb7c50bde9c4ccac979"
    url = "http://stb-artifacts//scottish-frs-data.tar.gz"

[scottish-lcf-expenditure]
git-tree-sha1 = "bf18d73b3f48bea065528bf63e43e522f85f5e4b"
lazy = true

    [[scottish-lcf-expenditure.download]]
    sha256 = "66231a2f9d4cf75d373812e6969e40ffe1dd386dc0b8c577aa3ed67f75e4cc1c"
    url = "http://stb-artifacts/scottish-lcf-expenditure.tar.gz"

[scottish-slab-legalaid]
git-tree-sha1 = "6ac253d4e01462d5fb25ba410a91504186c46f9d"
lazy = true

    [[scottish-slab-legalaid.download]]
    sha256 = "ec6dfe097d4dcceadb457261ff4ca1223f2c95a2642d541766ada87cfb6932e0"
    url = "http://stb-artifacts//scottish-slab-legalaid.tar.gz"

[scottish-synthetic-data]
git-tree-sha1 = "2bcdf3e7a62bb4bcd282f05008adbe6b63228ab9"
lazy = true

    [[scottish-synthetic-data.download]]
    sha256 = "701ac0c44fe997b7d4e252dc2bee65e2c8ae2cdb2b6975cf5ae8134c0188e2d5"
    url = "https://virtual-worlds.biz/artifacts//not-created-yet.tar.gz"

[scottish-synthetic-expenditure]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[scottish-synthetic-expenditure.download]]
    sha256 = "38f4f588974a40102a4b9998f9c0cea15001ec3d59f3e6b329a9659201cdb4c0"
    url = "https://virtual-worlds.biz/artifacts//scottish-synthetic-expenditure.tar.gz"

[scottish-synthetic-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[scottish-synthetic-wealth.download]]
    sha256 = "65a51554a00d8f8edd0f0c2df7cbcf3cbc4ad61428e331611671c8393c2e054d"
    url = "https://virtual-worlds.biz/artifacts//scottish-synthetic-wealth.tar.gz"

[scottish-was-wealth]
git-tree-sha1 = "f850d06c68ba5e10fe1d9c2eec9100c2e87cd5a9"
lazy = true

    [[scottish-was-wealth.download]]
    sha256 = "261af9f44c20fa4f9f56c059e92b6e869c1b7500add96385ab9fa9482584aa53"
    url = "http://stb-artifacts//scottish-was-wealth.tar.gz"

[uk-frs-data]
git-tree-sha1 = "8891ef02ea5dada4ec097ce0a183502cfafb995f"
lazy = true

    [[uk-frs-data.download]]
    sha256 = "8e3efc98a687441085be9ef5e53b663c2bd9abf6e300efa2dd6edb29993d8777"
    url = "http://stb-artifacts/model-data-2021-2021-v2.tar.gz"

[uk-lcf-expenditure]
git-tree-sha1 = "aac0e469d51d53ae54dcc2aa54af2d4f2d72a03a"
lazy = true

    [[uk-lcf-expenditure.download]]
    sha256 = "a2888101e82837d3cf9852fc35f66a36372d579b5660bf5cbf7a70cf11777187"
    url = "http://stb-artifacts/uk-lcf-expenditure.tar.gz"

[uk-synthetic-data]
git-tree-sha1 = "2bcdf3e7a62bb4bcd282f05008adbe6b63228ab9"
lazy = true

    [[uk-synthetic-data.download]]
    sha256 = "701ac0c44fe997b7d4e252dc2bee65e2c8ae2cdb2b6975cf5ae8134c0188e2d5"
    url = "https://virtual-worlds.biz/artifacts//not-created-yet.tar.gz"

[uk-synthetic-expenditure]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-synthetic-expenditure.download]]
    sha256 = "65593965ef048b2f9144b73e109a7dd25756df491929e63b5ff1b70e808e8d50"
    url = "https://virtual-worlds.biz/artifacts//uk-synthetic-expenditure.tar.gz"

[uk-synthetic-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-synthetic-wealth.download]]
    sha256 = "10fa81da7d1994cb804288cf02f575cdc6cb4a36b959a2d22a5638fa3a8c29a1"
    url = "https://virtual-worlds.biz/artifacts//uk-synthetic-wealth.tar.gz"

[uk-was-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-was-wealth.download]]
    sha256 = "d33b1c51eadb5f4bf8278f716a60b0a37ea7af66b8fe56dca045d50f7674d94f"
    url = "http://stb-artifacts/uk-was-wealth.tar.gz"
