[augdata]
git-tree-sha1 = "082e43c909e7970900ef80d04a70d7fa57ae4498"
lazy = true

    [[augdata.download]]
    sha256 = "c4ce7873df16a5b9f8e2c74296c89ba1b7ed407704a3af6811b6d9a72c09073b"
    url = "https://virtual-worlds.biz/artifacts//augdata.tar.gz"

[disability]
git-tree-sha1 = "288ef84eac1aad34af423852e64001e75be3b822"
lazy = true

    [[disability.download]]
    sha256 = "7ed1e796fc2e09a4c48f772ea3cd06b7c6aab721c183f6905b2fa83890d0184b"
    url = "https://virtual-worlds.biz/artifacts//disability.tar.gz"

[exampledata]
git-tree-sha1 = "7853136d3530ea531e4f45a29f8fcef81d08fc1c"
lazy = true

    [[exampledata.download]]
    sha256 = "c426f605704bde8c79df3573a4f150512614480aa00f900893accaf75408463c"
    url = "https://virtual-worlds.biz/artifacts//exampledata.tar.gz"

[scottish-frs-data]
git-tree-sha1 = "9c5c1e8a29e8f82d861100579cee3e3e49cae464"
lazy = true

    [[scottish-frs-data.download]]
    sha256 = "5bc1607882203127bd0c13ddeeb22deb0f51156cd65aa9f4c14af3c1df175ef2"
    url = "https://virtual-worlds.biz/artifacts//model-data-scotland-2015-2021-v2.tar.gz"

[scottish-lcf-expenditure]
git-tree-sha1 = "bf18d73b3f48bea065528bf63e43e522f85f5e4b"
lazy = true

    [[scottish-lcf-expenditure.download]]
    sha256 = "66231a2f9d4cf75d373812e6969e40ffe1dd386dc0b8c577aa3ed67f75e4cc1c"
    url = "https://virtual-worlds.biz/artifacts//scottish-lcf-expenditure.tar.gz"

[scottish-synthetic-data]
git-tree-sha1 = "2bcdf3e7a62bb4bcd282f05008adbe6b63228ab9"
lazy = true

    [[scottish-synthetic-data.download]]
    sha256 = "701ac0c44fe997b7d4e252dc2bee65e2c8ae2cdb2b6975cf5ae8134c0188e2d5"
    url = "https://virtual-worlds.biz/artifacts//not-created-yet.tar.gz"

[scottish-synthetic-expenditure]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[scottish-synthetic-expenditure.download]]
    sha256 = "38f4f588974a40102a4b9998f9c0cea15001ec3d59f3e6b329a9659201cdb4c0"
    url = "https://virtual-worlds.biz/artifacts//scottish-synthetic-expenditure.tar.gz"

[scottish-synthetic-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[scottish-synthetic-wealth.download]]
    sha256 = "65a51554a00d8f8edd0f0c2df7cbcf3cbc4ad61428e331611671c8393c2e054d"
    url = "https://virtual-worlds.biz/artifacts//scottish-synthetic-wealth.tar.gz"

[scottish-was-wealth]
git-tree-sha1 = "56ad24d4adee3965f683c43b4339ec0c89c4cb68"
lazy = true

    [[scottish-was-wealth.download]]
    sha256 = "6a6f5a25f22a102bb0b3e770a874b54d19407a1bafbdd6bd7956477c1204fb46"
    url = "https://virtual-worlds.biz/artifacts//scottish-was-wealth.tar.gz"

[uk-frs-data]
git-tree-sha1 = "8891ef02ea5dada4ec097ce0a183502cfafb995f"
lazy = true

    [[uk-frs-data.download]]
    sha256 = "8e3efc98a687441085be9ef5e53b663c2bd9abf6e300efa2dd6edb29993d8777"
    url = "https://virtual-worlds.biz/artifacts//model-data-2021-2021-v2.tar.gz"

[uk-lcf-expenditure]
git-tree-sha1 = "75780fa203742d35c05e345ea26daa4b2e803280"
lazy = true

    [[uk-lcf-expenditure.download]]
    sha256 = "3cc8b249fb7e9e8e50b2ac719165d4dbe6e79ddbd9a57f444b9e0a7fc0f11f4c"
    url = "https://virtual-worlds.biz/artifacts//uk-lcf-expenditure.tar.gz"

[uk-synthetic-data]
git-tree-sha1 = "2bcdf3e7a62bb4bcd282f05008adbe6b63228ab9"
lazy = true

    [[uk-synthetic-data.download]]
    sha256 = "701ac0c44fe997b7d4e252dc2bee65e2c8ae2cdb2b6975cf5ae8134c0188e2d5"
    url = "https://virtual-worlds.biz/artifacts//not-created-yet.tar.gz"

[uk-synthetic-expenditure]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-synthetic-expenditure.download]]
    sha256 = "65593965ef048b2f9144b73e109a7dd25756df491929e63b5ff1b70e808e8d50"
    url = "https://virtual-worlds.biz/artifacts//uk-synthetic-expenditure.tar.gz"

[uk-synthetic-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-synthetic-wealth.download]]
    sha256 = "10fa81da7d1994cb804288cf02f575cdc6cb4a36b959a2d22a5638fa3a8c29a1"
    url = "https://virtual-worlds.biz/artifacts//uk-synthetic-wealth.tar.gz"

[uk-was-wealth]
git-tree-sha1 = "8fb7e3a1d9da7de2a9b1f91a05a8c431f8ab4526"
lazy = true

    [[uk-was-wealth.download]]
    sha256 = "d33b1c51eadb5f4bf8278f716a60b0a37ea7af66b8fe56dca045d50f7674d94f"
    url = "https://virtual-worlds.biz/artifacts//uk-was-wealth.tar.gz"
