baseurl: https://stb-blog.virtual-worlds.scot
title: Scottish Tax Benefit Model Blog
subtitle: A little blog about microsimulaton
author: Graham Stark
simple_search: http://google.com/search
description: A blog about building a simulation model
name: Scottish Tax Benefit Model Blog
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:year/:month/:day/:title:output_ext
timezone:  Europe/London
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
excerpt_separator: <!--more-->
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: 
